spring.datasource.url=jdbc:mysql://localhost:3306/bankingminisystem
spring.datasource.username=root
spring.datasource.password=prasanth007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true